name: code validations

on:
  push

jobs:
  validate_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate code
      run: |
        echo "Validating code"
        echo "Code is valid"
