name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: 'Joe'
      color:
        description: 'Favorite Color'
        required: false
        default: 'Mother of pearl'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ input_name }}"
        echo "I see your favorite color is ${{ input_color }}.  OMGoodness, that's mine too!"
