name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: 'Joe'
      color:
        description: 'Favorite Color'
        required: false
        default: 'Mother of pearl'
      tags:
        description: 'JSON to define tags'
        required: false
        default: '{}'


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ inputs.name }}"
        echo "I see your favorite color is ${{ inputs.color }}.  OMGoodness, that's mine too!"
        echo "Here is a list of the tags defined"
        echo "${{ inputs.tags }}"
