name: Test EC2 Deployment

on: workflow_dispatch

jobs:
  terraform:
    name: "Terraform Cloud Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use branch workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          path: terraform
          workspace: samplews