name: Test EC2 Deployment

on: workflow_dispatch

jobs:
  terraform:
    name: "Terraform Cloud Test"
    runs-on: ubuntu-latest
    env:
      TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Create Workspace"
        id: workspace
        uses: recarnot/terraform-github-workspace-setup-action@master
        with:
          organization: "AHEAD-Demo"
          workspace: "samplews"
          token: ${{ secrets.TF_API_TOKEN }}
          vars: '
            {
              "key": "region",
              "value": "eu-west-3",
              "sensitive": "false"
            },
            {
              "key": "access_key_id",
              "value": "${{ secrets.AWS_ACCESS_KEY_ID }}",
              "sensitive": "true"
            },
            {
              "key": "access_key_secret",
              "value": "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
              "sensitive": "true"
            }'

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: test-app

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: test-app
