name: Test EC2 Deployment

on: workflow_dispatch

jobs:
  terraform:
    name: "Terraform Cloud Test"
    runs-on: ubuntu-latest
    env:
      TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use branch workspace
        uses: dflook/terraform-new-workspace@v1
        env:
          TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_API_TOKEN }}
        with:
          path: test-app
          workspace: samplews